import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, Archive, BarChart3, Bell, CalendarDays, Check, ChevronDown, CircleHelp, Filter, GitBranch, LayoutDashboard, MoreHorizontal, Plus, Search, Settings2, SlidersHorizontal, Sparkles, Users, X, Zap } from 'lucide-react';
import { Area, CartesianGrid, ComposedChart, Line, ReferenceDot, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import './styles.css';

type Status = 'todo'|'in_progress'|'in_review'|'done';
type Task = { id:number; title:string; points:number; status:Status; priority:'P0'|'P1'|'P2'|'P3'; assignee?:string; tag?:string };
type Change = { day:string; time:string; type:'add'|'remove'|'change'; title:string; delta:number; reason:string; by:string };

const seedTasks: Task[] = [
  {id:1,title:'支付接口基础设施',points:3,status:'done',priority:'P0',assignee:'SM',tag:'Backend'},
  {id:2,title:'微信支付渠道接入',points:5,status:'in_progress',priority:'P0',assignee:'AL',tag:'Backend'},
  {id:3,title:'退款流程与状态同步',points:3,status:'in_review',priority:'P1',assignee:'JK',tag:'Payments'},
  {id:4,title:'支付结果页优化',points:2,status:'todo',priority:'P2',assignee:'SM',tag:'Frontend'},
  {id:5,title:'对账报表',points:3,status:'todo',priority:'P2',assignee:'AL',tag:'Data'},
  {id:6,title:'订单异常告警',points:2,status:'todo',priority:'P1',assignee:'JK',tag:'Ops'},
  {id:7,title:'埋点与转化漏斗',points:2,status:'done',priority:'P3',assignee:'SM',tag:'Analytics'},
];
const changes: Change[] = [
  {day:'Day 5',time:'14:30',type:'remove',title:'移除「对账报表」',delta:-3,reason:'优先级降低',by:'老王'},
  {day:'Day 3',time:'09:15',type:'add',title:'新增「微信支付渠道接入」',delta:5,reason:'老板要求',by:'老王'},
  {day:'Day 1',time:'09:00',type:'change',title:'Sprint 开始',delta:16,reason:'初始范围',by:'小明'},
];
const chartData = [{day:'D1',scope:16,completed:0,ideal:0},{day:'D2',scope:16,completed:2,ideal:2.3},{day:'D3',scope:21,completed:5,ideal:4.6,change:5},{day:'D4',scope:21,completed:8,ideal:6.9},{day:'D5',scope:18,completed:10,ideal:9.2,change:-3},{day:'D6',scope:18,completed:12,ideal:11.5},{day:'D7',scope:18,completed:13,ideal:13.8},{day:'D8',scope:18,completed:13,ideal:16}];

function App(){
  const [tasks,setTasks]=useState(seedTasks); const [view,setView]=useState<'burnup'|'burndown'>('burnup'); const [selected,setSelected]=useState<Task|null>(null); const [showAdd,setShowAdd]=useState(false); const [query,setQuery]=useState('');
  const filtered=useMemo(()=>tasks.filter(t=>t.title.toLowerCase().includes(query.toLowerCase())),[tasks,query]);
  const done=tasks.filter(t=>t.status==='done').reduce((a,t)=>a+t.points,0); const total=tasks.reduce((a,t)=>a+t.points,0); const completedPct=Math.round(done/18*100);
  const move=(id:number,status:Status)=>setTasks(ts=>ts.map(t=>t.id===id?{...t,status}:t));
  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><div className="brand-mark"><Zap size={16} fill="currentColor"/></div><span>vibe<span className="brand-accent">pm</span></span></div>
      <div className="workspace-switch"><div className="workspace-icon">V</div><div><b>Vibe PM</b><small>Personal workspace</small></div><ChevronDown size={15}/></div>
      <nav><Nav icon={<LayoutDashboard size={17}/>} label="Overview" active/><Nav icon={<Activity size={17}/>} label="Sprint board"/><Nav icon={<BarChart3 size={17}/>} label="Reports"/><Nav icon={<Archive size={17}/>} label="Backlog"/></nav>
      <div className="nav-label">WORKSPACE</div><nav><Nav icon={<Users size={17}/>} label="Members"/><Nav icon={<GitBranch size={17}/>} label="Integrations"/></nav><div className="sidebar-bottom"><Nav icon={<Settings2 size={17}/>} label="Settings"/><div className="user"><div className="avatar avatar-purple">XM</div><div><b>小明</b><small>Tech Lead</small></div><MoreHorizontal size={16}/></div></div>
    </aside>
    <main className="main"><header className="topbar"><div className="breadcrumbs"><span>Vibe PM</span><span>/</span><b>Sprint 14</b><span className="status-pill active"><i/> Active</span></div><div className="top-actions"><button className="icon-btn" title="Search"><Search size={18}/></button><button className="icon-btn" title="Notifications"><Bell size={18}/><em/></button><div className="avatar avatar-blue">XM</div></div></header>
      <div className="content"><div className="page-head"><div><div className="eyebrow">CURRENT SPRINT <span>•</span> 8 DAYS LEFT</div><h1>Build the payment flow</h1><p>Make checkout feel effortless for every customer.</p></div><div className="head-actions"><button className="ghost-btn"><CalendarDays size={16}/> Jun 03 – Jun 14 <ChevronDown size={14}/></button><button className="primary-btn" onClick={()=>setShowAdd(true)}><Plus size={17}/> Add task</button></div></div>
      <section className="metrics"><Metric label="Scope" value={`${total} pt`} note="+2 pt this sprint" tone="blue"/><Metric label="Completed" value={`${done} pt`} note={`${completedPct}% of scope`} tone="green"/><Metric label="Remaining" value={`${total-done} pt`} note="On track to finish" tone="orange"/><Metric label="Scope changes" value="2" note="+5 / −3 pt" tone="purple"/></section>
      <section className="grid-main"><div className="chart-card panel"><div className="panel-head"><div><h2>Scope & progress</h2><p>Burnup chart · Daily snapshots</p></div><div className="segmented"><button className={view==='burnup'?'selected':''} onClick={()=>setView('burnup')}>Burnup</button><button className={view==='burndown'?'selected':''} onClick={()=>setView('burndown')}>Burndown</button></div></div><div className="legend"><span><i className="line blue"/> Scope</span><span><i className="line green"/> Completed</span><span><i className="line ideal"/> Ideal pace</span><span className="legend-change"><i/> Scope change</span></div><div className="chart-wrap"><ResponsiveContainer width="100%" height={285}><ComposedChart data={chartData} margin={{top:12,right:10,left:-18,bottom:0}}><defs><linearGradient id="fillGreen" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#31c48d" stopOpacity={.22}/><stop offset="100%" stopColor="#31c48d" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#edf0f4"/><XAxis dataKey="day" axisLine={false} tickLine={false} tick={{fill:'#8d96a5',fontSize:11}}/><YAxis axisLine={false} tickLine={false} tick={{fill:'#8d96a5',fontSize:11}} domain={[0,24]} ticks={[0,6,12,18,24]}/><Tooltip content={<ChartTooltip/>}/>{view==='burnup'?<><Area type="monotone" dataKey="completed" stroke="none" fill="url(#fillGreen)"/><Line type="monotone" dataKey="completed" stroke="#31c48d" strokeWidth={3} dot={false}/><Line type="stepAfter" dataKey="scope" stroke="#4679f6" strokeWidth={2.5} dot={false}/><Line type="monotone" dataKey="ideal" stroke="#aab2bf" strokeDasharray="5 5" strokeWidth={1.5} dot={false}/></>:<><Line type="monotone" dataKey="remaining" stroke="#ef6868" strokeWidth={3} dot={false}/><Line type="monotone" dataKey="idealRemaining" stroke="#aab2bf" strokeDasharray="5 5" strokeWidth={1.5} dot={false}/></>}{chartData.filter(d=>d.change).map(d=><ReferenceDot key={d.day} x={d.day} y={d.scope} r={5} fill={d.change!>0?'#ef6868':'#31c48d'} stroke="#fff" strokeWidth={2}/>)}</ComposedChart></ResponsiveContainer></div><div className="chart-foot"><div><span>Current scope</span><b>18 pt</b></div><div><span>Completed</span><b className="green-text">13 pt</b></div><div><span>Remaining</span><b>5 pt</b></div><div><span>Velocity</span><b>2.1 pt/day</b></div></div></div>
        <aside className="timeline panel"><div className="panel-head"><div><h2>Scope changes</h2><p>Everything that moved the line</p></div><button className="icon-btn"><SlidersHorizontal size={17}/></button></div><div className="timeline-list">{changes.map((c,i)=><div className="timeline-item" key={i}><div className={`timeline-dot ${c.type}`}>{c.type==='add'?'+':c.type==='remove'?'−':'•'}</div><div className="timeline-content"><div className="timeline-meta"><b>{c.day}</b><span>{c.time}</span></div><strong>{c.title}</strong><div className="timeline-detail"><span className={`delta ${c.delta>0?'up':'down'}`}>{c.delta>0?'+':''}{c.delta} pt</span><span>{c.reason}</span></div><small>by {c.by}</small></div></div>)}</div><button className="view-all">View full timeline <span>→</span></button></aside></section>
      <section className="board panel"><div className="panel-head board-head"><div><h2>Sprint board</h2><p>Move cards as work moves forward.</p></div><div className="board-tools"><div className="search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Filter tasks..."/></div><button className="ghost-btn"><Filter size={15}/> Filter</button></div></div><div className="columns">{(['todo','in_progress','in_review','done'] as Status[]).map(status=><Column key={status} status={status} tasks={filtered.filter(t=>t.status===status)} onMove={move} onSelect={setSelected}/>)}</div></section>
      </div>
    </main>
    {selected&&<div className="overlay" onClick={()=>setSelected(null)}><div className="drawer" onClick={e=>e.stopPropagation()}><div className="drawer-head"><span>Task details</span><button className="icon-btn" onClick={()=>setSelected(null)}><X size={18}/></button></div><div className="drawer-body"><div className="task-title-row"><span className={`priority p-${selected.priority}`}>{selected.priority}</span><h2>{selected.title}</h2></div><p className="drawer-desc">Keep this work visible, focused and easy to explain during the sprint review.</p><div className="drawer-grid"><div><label>Status</label><select value={selected.status} onChange={e=>{move(selected.id,e.target.value as Status);setSelected({...selected,status:e.target.value as Status})}}><option value="todo">Todo</option><option value="in_progress">In progress</option><option value="in_review">In review</option><option value="done">Done</option></select></div><div><label>Story points</label><div className="point-control">{selected.points} pt <ChevronDown size={14}/></div></div></div><div className="assignee-row"><div className="avatar avatar-blue">{selected.assignee}</div><div><label>Assignee</label><b>{selected.assignee==='SM'?'小明':selected.assignee==='AL'?'Alex':'Jing'}</b></div></div><button className="primary-btn full" onClick={()=>setSelected(null)}><Check size={16}/> Save changes</button></div></div></div>}
    {showAdd&&<div className="overlay" onClick={()=>setShowAdd(false)}><div className="modal" onClick={e=>e.stopPropagation()}><div className="drawer-head"><div><span className="eyebrow">NEW TASK</span><h2>Add to Sprint 14</h2></div><button className="icon-btn" onClick={()=>setShowAdd(false)}><X size={18}/></button></div><form onSubmit={e=>{e.preventDefault();setShowAdd(false)}}><label>Task title<input autoFocus required placeholder="What needs to be done?"/></label><div className="drawer-grid"><label>Story points<select defaultValue="3"><option>1</option><option>2</option><option>3</option><option>5</option><option>8</option><option>13</option></select></label><label>Priority<select defaultValue="P2"><option>P0</option><option>P1</option><option>P2</option><option>P3</option></select></label></div><label>Reason for adding <span className="optional">optional</span><textarea placeholder="Why is this entering the sprint?"/></label><button className="primary-btn full" type="submit"><Plus size={16}/> Add task</button></form></div></div>}
  </div>
}
function Nav({icon,label,active}:{icon:React.ReactNode;label:string;active?:boolean}){return <button className={`nav-item ${active?'active':''}`}>{icon}<span>{label}</span>{active&&<i/>}</button>}
function Metric({label,value,note,tone}:{label:string;value:string;note:string;tone:string}){return <div className="metric"><div className={`metric-icon ${tone}`}><Activity size={16}/></div><div><span>{label}</span><b>{value}</b><small>{note}</small></div></div>}
function Column({status,tasks,onMove,onSelect}:{status:Status;tasks:Task[];onMove:(id:number,s:Status)=>void;onSelect:(t:Task)=>void}){const labels={todo:'Todo',in_progress:'In progress',in_review:'In review',done:'Done'};return <div className="column"><div className="column-head"><div><b>{labels[status]}</b><span>{tasks.length}</span></div><button className="icon-btn"><Plus size={16}/></button></div><div className="task-list" onDragOver={e=>e.preventDefault()} onDrop={e=>{const id=Number(e.dataTransfer.getData('id'));if(id)onMove(id,status)}}>{tasks.map(t=><div className="task-card" key={t.id} draggable onDragStart={e=>e.dataTransfer.setData('id',String(t.id))} onClick={()=>onSelect(t)}><div className="task-top"><span className={`priority p-${t.priority}`}>{t.priority}</span><button className="icon-btn"><MoreHorizontal size={15}/></button></div><h3>{t.title}</h3><div className="task-bottom"><span className="points"><Zap size={12}/>{t.points}</span><span className="tag">{t.tag}</span><div className={`avatar avatar-${t.assignee==='SM'?'purple':t.assignee==='AL'?'blue':'orange'}`}>{t.assignee}</div></div></div>)}</div></div>}
function ChartTooltip({active,payload,label}:{active?:boolean;payload?:any[];label?:string}){if(!active||!payload?.length)return null;return <div className="chart-tooltip"><b>{label}</b>{payload.map(p=><div key={p.dataKey}><span style={{color:p.color}}>●</span>{p.dataKey==='scope'?'Scope':p.dataKey==='completed'?'Completed':'Ideal pace'} <strong>{p.value} pt</strong></div>)}</div>}
createRoot(document.getElementById('root')!).render(<App/>);
