import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, Archive, BarChart3, Bell, CalendarDays, Check, ChevronDown, CircleHelp, Filter, GitBranch, LayoutDashboard, MoreHorizontal, Plus, Search, Settings2, SlidersHorizontal, Sparkles, Users, X, Zap } from 'lucide-react';
import { Area, CartesianGrid, ComposedChart, Line, ReferenceDot, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import './styles.css';

type Status = 'todo'|'in_progress'|'in_review'|'done';
type Task = { id:number; title:string; points:number; status:Status; priority:'P0'|'P1'|'P2'|'P3'; assignee?:string; tag?:string };
type Change = { day:string; time:string; type:'add'|'remove'|'change'; title:string; delta:number; reason:string; by:string };

const seedTasks: Task[] = [
  {id:1,title:'支付接口基础设施',points:3,status:'done',priority:'P0',assignee:'SM',tag:'后端'},
  {id:2,title:'微信支付渠道接入',points:5,status:'in_progress',priority:'P0',assignee:'AL',tag:'后端'},
  {id:3,title:'退款流程与状态同步',points:3,status:'in_review',priority:'P1',assignee:'JK',tag:'支付'},
  {id:4,title:'支付结果页优化',points:2,status:'todo',priority:'P2',assignee:'SM',tag:'前端'},
  {id:5,title:'对账报表',points:3,status:'todo',priority:'P2',assignee:'AL',tag:'数据'},
  {id:6,title:'订单异常告警',points:2,status:'todo',priority:'P1',assignee:'JK',tag:'运维'},
  {id:7,title:'埋点与转化漏斗',points:2,status:'done',priority:'P3',assignee:'SM',tag:'分析'},
];
const changes: Change[] = [
  {day:'Day 5',time:'14:30',type:'remove',title:'移除「对账报表」',delta:-3,reason:'优先级降低',by:'老王'},
  {day:'Day 3',time:'09:15',type:'add',title:'新增「微信支付渠道接入」',delta:5,reason:'老板要求',by:'老王'},
  {day:'Day 1',time:'09:00',type:'change',title:'Sprint 开始',delta:16,reason:'初始范围',by:'小明'},
];
const chartData = [{day:'第1天',scope:16,completed:0,ideal:0},{day:'第2天',scope:16,completed:2,ideal:2.3},{day:'第3天',scope:21,completed:5,ideal:4.6,change:5},{day:'第4天',scope:21,completed:8,ideal:6.9},{day:'第5天',scope:18,completed:10,ideal:9.2,change:-3},{day:'第6天',scope:18,completed:12,ideal:11.5},{day:'第7天',scope:18,completed:13,ideal:13.8},{day:'第8天',scope:18,completed:13,ideal:16}];

function App(){
  const [tasks,setTasks]=useState(seedTasks); const [view,setView]=useState<'burnup'|'burndown'>('burnup'); const [selected,setSelected]=useState<Task|null>(null); const [showAdd,setShowAdd]=useState(false); const [query,setQuery]=useState('');
  const filtered=useMemo(()=>tasks.filter(t=>t.title.toLowerCase().includes(query.toLowerCase())),[tasks,query]);
  const done=tasks.filter(t=>t.status==='done').reduce((a,t)=>a+t.points,0); const total=tasks.reduce((a,t)=>a+t.points,0); const completedPct=Math.round(done/18*100);
  const move=(id:number,status:Status)=>setTasks(ts=>ts.map(t=>t.id===id?{...t,status}:t));
  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><div className="brand-mark"><Zap size={16} fill="currentColor"/></div><span>vibe<span className="brand-accent">pm</span></span></div>
      <div className="workspace-switch"><div className="workspace-icon">V</div><div><b>Vibe PM</b><small>个人工作区</small></div><ChevronDown size={15}/></div>
      <nav><Nav icon={<LayoutDashboard size={17}/>} label="总览" active/><Nav icon={<Activity size={17}/>} label="Sprint 看板"/><Nav icon={<BarChart3 size={17}/>} label="报告"/><Nav icon={<Archive size={17}/>} label="待办列表"/></nav>
      <div className="nav-label">工作区</div><nav><Nav icon={<Users size={17}/>} label="成员"/><Nav icon={<GitBranch size={17}/>} label="集成"/></nav><div className="sidebar-bottom"><Nav icon={<Settings2 size={17}/>} label="设置"/><div className="user"><div className="avatar avatar-purple">XM</div><div><b>小明</b><small>技术负责人</small></div><MoreHorizontal size={16}/></div></div>
    </aside>
    <main className="main"><header className="topbar"><div className="breadcrumbs"><span>Vibe PM</span><span>/</span><b>Sprint 14</b><span className="status-pill active"><i/> 进行中</span></div><div className="top-actions"><button className="icon-btn" title="搜索"><Search size={18}/></button><button className="icon-btn" title="通知"><Bell size={18}/><em/></button><div className="avatar avatar-blue">XM</div></div></header>
      <div className="content"><div className="page-head"><div><div className="eyebrow">当前迭代 <span>•</span> 剩余 8 天</div><h1>完成支付流程</h1><p>让每位客户都能轻松完成结账。</p></div><div className="head-actions"><button className="ghost-btn"><CalendarDays size={16}/> 6月03日 – 6月14日 <ChevronDown size={14}/></button><button className="primary-btn" onClick={()=>setShowAdd(true)}><Plus size={17}/> 添加任务</button></div></div>
      <section className="metrics"><Metric label="范围" value={`${total} pt`} note="本迭代 +2 pt" tone="blue"/><Metric label="已完成" value={`${done} pt`} note={`范围的 ${completedPct}%`} tone="green"/><Metric label="剩余" value={`${total-done} pt`} note="按计划推进" tone="orange"/><Metric label="范围变更" value="2" note="+5 / −3 pt" tone="purple"/></section>
      <section className="grid-main"><div className="chart-card panel"><div className="panel-head"><div><h2>范围与进度</h2><p>燃起图 · 每日快照</p></div><div className="segmented"><button className={view==='burnup'?'selected':''} onClick={()=>setView('burnup')}>燃起图</button><button className={view==='burndown'?'selected':''} onClick={()=>setView('burndown')}>燃尽图</button></div></div><div className="legend"><span><i className="line blue"/> 范围</span><span><i className="line green"/> 已完成</span><span><i className="line ideal"/> 理想进度</span><span className="legend-change"><i/> 范围变更</span></div><div className="chart-wrap"><ResponsiveContainer width="100%" height={285}><ComposedChart data={chartData} margin={{top:12,right:10,left:-18,bottom:0}}><defs><linearGradient id="fillGreen" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#31c48d" stopOpacity={.22}/><stop offset="100%" stopColor="#31c48d" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#edf0f4"/><XAxis dataKey="day" axisLine={false} tickLine={false} tick={{fill:'#8d96a5',fontSize:11}}/><YAxis axisLine={false} tickLine={false} tick={{fill:'#8d96a5',fontSize:11}} domain={[0,24]} ticks={[0,6,12,18,24]}/><Tooltip content={<ChartTooltip/>}/>{view==='burnup'?<><Area type="monotone" dataKey="completed" stroke="none" fill="url(#fillGreen)"/><Line type="monotone" dataKey="completed" stroke="#31c48d" strokeWidth={3} dot={false}/><Line type="stepAfter" dataKey="scope" stroke="#4679f6" strokeWidth={2.5} dot={false}/><Line type="monotone" dataKey="ideal" stroke="#aab2bf" strokeDasharray="5 5" strokeWidth={1.5} dot={false}/></>:<><Line type="monotone" dataKey="remaining" stroke="#ef6868" strokeWidth={3} dot={false}/><Line type="monotone" dataKey="idealRemaining" stroke="#aab2bf" strokeDasharray="5 5" strokeWidth={1.5} dot={false}/></>}{chartData.filter(d=>d.change).map(d=><ReferenceDot key={d.day} x={d.day} y={d.scope} r={5} fill={d.change!>0?'#ef6868':'#31c48d'} stroke="#fff" strokeWidth={2}/>)}</ComposedChart></ResponsiveContainer></div><div className="chart-foot"><div><span>当前范围</span><b>18 pt</b></div><div><span>已完成</span><b className="green-text">13 pt</b></div><div><span>剩余</span><b>5 pt</b></div><div><span>每日速度</span><b>2.1 pt/天</b></div></div></div>
        <aside className="timeline panel"><div className="panel-head"><div><h2>范围变更</h2><p>所有影响范围线的变化</p></div><button className="icon-btn" title="筛选"><SlidersHorizontal size={17}/></button></div><div className="timeline-list">{changes.map((c,i)=><div className="timeline-item" key={i}><div className={`timeline-dot ${c.type}`}>{c.type==='add'?'+':c.type==='remove'?'−':'•'}</div><div className="timeline-content"><div className="timeline-meta"><b>{c.day.replace('Day','第')}天</b><span>{c.time}</span></div><strong>{c.title}</strong><div className="timeline-detail"><span className={`delta ${c.delta>0?'up':'down'}`}>{c.delta>0?'+':''}{c.delta} pt</span><span>{c.reason}</span></div><small>操作人：{c.by}</small></div></div>)}</div><button className="view-all">查看完整时间线 <span>→</span></button></aside></section>
      <section className="board panel"><div className="panel-head board-head"><div><h2>Sprint 看板</h2><p>随着工作推进移动任务卡片。</p></div><div className="board-tools"><div className="search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="筛选任务…"/></div><button className="ghost-btn"><Filter size={15}/> 筛选</button></div></div><div className="columns">{(['todo','in_progress','in_review','done'] as Status[]).map(status=><Column key={status} status={status} tasks={filtered.filter(t=>t.status===status)} onMove={move} onSelect={setSelected}/>)}</div></section>
      </div>
    </main>
    {selected&&<div className="overlay" onClick={()=>setSelected(null)}><div className="drawer" onClick={e=>e.stopPropagation()}><div className="drawer-head"><span>任务详情</span><button className="icon-btn" title="关闭" onClick={()=>setSelected(null)}><X size={18}/></button></div><div className="drawer-body"><div className="task-title-row"><span className={`priority p-${selected.priority}`}>{selected.priority}</span><h2>{selected.title}</h2></div><p className="drawer-desc">让这项工作保持清晰、专注，便于在 Sprint 复盘时说明。</p><div className="drawer-grid"><div><label>状态</label><select value={selected.status} onChange={e=>{move(selected.id,e.target.value as Status);setSelected({...selected,status:e.target.value as Status})}}><option value="todo">待办</option><option value="in_progress">进行中</option><option value="in_review">待审核</option><option value="done">已完成</option></select></div><div><label>故事点</label><div className="point-control">{selected.points} pt <ChevronDown size={14}/></div></div></div><div className="assignee-row"><div className="avatar avatar-blue">{selected.assignee}</div><div><label>负责人</label><b>{selected.assignee==='SM'?'小明':selected.assignee==='AL'?'Alex':'Jing'}</b></div></div><button className="primary-btn full" onClick={()=>setSelected(null)}><Check size={16}/> 保存修改</button></div></div></div>}
    {showAdd&&<div className="overlay" onClick={()=>setShowAdd(false)}><div className="modal" onClick={e=>e.stopPropagation()}><div className="drawer-head"><div><span className="eyebrow">新建任务</span><h2>添加到 Sprint 14</h2></div><button className="icon-btn" title="关闭" onClick={()=>setShowAdd(false)}><X size={18}/></button></div><form onSubmit={e=>{e.preventDefault();setShowAdd(false)}}><label>任务标题<input autoFocus required placeholder="需要完成什么？"/></label><div className="drawer-grid"><label>故事点<select defaultValue="3"><option>1</option><option>2</option><option>3</option><option>5</option><option>8</option><option>13</option></select></label><label>优先级<select defaultValue="P2"><option>P0</option><option>P1</option><option>P2</option><option>P3</option></select></label></div><label>添加原因 <span className="optional">选填</span><textarea placeholder="为什么要将它加入本次 Sprint？"/></label><button className="primary-btn full" type="submit"><Plus size={16}/> 添加任务</button></form></div></div>}
  </div>
}
function Nav({icon,label,active}:{icon:React.ReactNode;label:string;active?:boolean}){return <button className={`nav-item ${active?'active':''}`}>{icon}<span>{label}</span>{active&&<i/>}</button>}
function Metric({label,value,note,tone}:{label:string;value:string;note:string;tone:string}){return <div className="metric"><div className={`metric-icon ${tone}`}><Activity size={16}/></div><div><span>{label}</span><b>{value}</b><small>{note}</small></div></div>}
function Column({status,tasks,onMove,onSelect}:{status:Status;tasks:Task[];onMove:(id:number,s:Status)=>void;onSelect:(t:Task)=>void}){const labels={todo:'待办',in_progress:'进行中',in_review:'待审核',done:'已完成'};return <div className="column"><div className="column-head"><div><b>{labels[status]}</b><span>{tasks.length}</span></div><button className="icon-btn" title="添加任务"><Plus size={16}/></button></div><div className="task-list" onDragOver={e=>e.preventDefault()} onDrop={e=>{const id=Number(e.dataTransfer.getData('id'));if(id)onMove(id,status)}}>{tasks.map(t=><div className="task-card" key={t.id} draggable onDragStart={e=>e.dataTransfer.setData('id',String(t.id))} onClick={()=>onSelect(t)}><div className="task-top"><span className={`priority p-${t.priority}`}>{t.priority}</span><button className="icon-btn" title="更多操作"><MoreHorizontal size={15}/></button></div><h3>{t.title}</h3><div className="task-bottom"><span className="points"><Zap size={12}/>{t.points}</span><span className="tag">{t.tag}</span><div className={`avatar avatar-${t.assignee==='SM'?'purple':t.assignee==='AL'?'blue':'orange'}`}>{t.assignee}</div></div></div>)}</div></div>}
function ChartTooltip({active,payload,label}:{active?:boolean;payload?:any[];label?:string}){if(!active||!payload?.length)return null;return <div className="chart-tooltip"><b>{label}</b>{payload.map(p=><div key={p.dataKey}><span style={{color:p.color}}>●</span>{p.dataKey==='scope'?'范围':p.dataKey==='completed'?'已完成':p.dataKey==='remaining'?'剩余':'理想进度'} <strong>{p.value} pt</strong></div>)}</div>}
createRoot(document.getElementById('root')!).render(<App/>);
